In [1]:
import array

In [2]:
ls=list(range(10))

In [3]:
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
var=array.array('i',ls) # in  indicate the integer here 

In [6]:
var

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import numpy as np

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# np.empty(5)

In [32]:
#value will be whatever if already exit in memory 
#It's show the memory allocation

### Data types of Numpy 
- boolen (true or false )
- int "$int32$ and $int64$" , ("int8" , use in indxing )
- float  "$float32$" and "$float64$"
- complex $complex64$ and the "$complex32$" comes under the float


In [33]:
# seed 

In [41]:
x=np.random.seed(10)

In [50]:
var1=np.random.randint(10,size=6)
var2=np.random.randint(10,size=(4,5))
var3=np.random.randint(10,size=(4,5,6))

In [58]:
print("the diminsion",var1.ndim) 
print("the shape of value",var2.shape)
print("the size is ",var3.size)
print("the dtype is ",var3.dtype)

the diminsion 1
the shape of value (4, 5)
the size is  120
the dtype is  int32


In [59]:
var1

array([5, 8, 9, 9, 1, 5])

In [60]:
#scrap the value from the array
var1[-1]

5

In [61]:
var2[0][0]

9

In [62]:
var2

array([[9, 1, 4, 7, 7],
       [7, 9, 7, 6, 0],
       [3, 9, 4, 4, 6],
       [8, 4, 9, 2, 1]])

In [67]:
#var2[3][0] # i am very happy 
#from second row strach 3,4 column
var2[3,0]

8

In [65]:
var2[1,3] #this is called indexing

6

In [74]:
#slicing here [start: stop: step]

In [79]:
var1[4:5]

array([1])

In [83]:
# indexing value [1,2,3,4,]
                  #[0,1,2,3]
#slicing [ value form A point to B point ]

In [84]:
var2

array([[9, 1, 4, 7, 7],
       [7, 9, 7, 6, 0],
       [3, 9, 4, 4, 6],
       [8, 4, 9, 2, 1]])

In [94]:
var2[2:3,2:4]

array([[4, 4]])

In [96]:
var2[:3,:2]

array([[9, 1],
       [7, 9],
       [3, 9]])

In [100]:
var2

array([[9, 1, 4, 7, 7],
       [7, 9, 7, 6, 0],
       [3, 9, 4, 4, 6],
       [8, 4, 9, 2, 1]])

In [103]:
var2[::-1,::-1]

array([[1, 2, 9, 4, 8],
       [6, 4, 4, 9, 3],
       [0, 6, 7, 9, 7],
       [7, 7, 4, 1, 9]])

In [104]:
#Reshaping the array

In [120]:
var4=np.arange(1,10).reshape(3,3)

##### example reshape
- you have called emp table here present only 1 row and you have 5 columns
- you have and another data department table they 2 rows and 10 columns 

In [121]:
var4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
var4

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [123]:
var=np.array([1,2,3,4,5,6])
var

array([1, 2, 3, 4, 5, 6])

In [124]:
var.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [125]:
var.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [130]:
x=np.arange(1,5).reshape(2,2)

In [131]:
x

array([[1, 2],
       [3, 4]])

In [134]:
var5=np.arange(1,5)
var6=np.arange(6,10)

In [135]:
print(var5)
print(var6)

[1 2 3 4]
[6 7 8 9]


In [136]:
var7=np.concatenate([var5,var6])

In [138]:
var8=np.concatenate([var5,var6,var7])

In [139]:
var8

array([1, 2, 3, 4, 6, 7, 8, 9, 1, 2, 3, 4, 6, 7, 8, 9])

In [141]:
#split function in numpy
#same as the stering and we done list perivously

In [142]:
var9=np.arange(1,11)

In [144]:
var9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
var10=np.split(var9,[3])

In [148]:
var10

[array([1, 2, 3]), array([ 4,  5,  6,  7,  8,  9, 10])]

In [170]:
#now we split this in to more array
var11,var12,var13=np.split(var9,[3,5])

In [173]:
print(var13)

[ 6  7  8  9 10]


## Arthmatic  UFunction in NumPy
- np.add (+)
- np.substract (-)
- np.multiply (*)
- np.division (/)
- np.floor  (//)
- np.mod (%)
- np.power (**)
- np.squrt (**)

In [174]:
a1=np.array([11,99,55,42,-20,6,0,-13])

In [175]:
a1

array([ 11,  99,  55,  42, -20,   6,   0, -13])

In [176]:
a2=np.abs(a1) #absoulute function of numpy

In [177]:
a2

array([11, 99, 55, 42, 20,  6,  0, 13])

In [189]:
a3= np.arange(5)

In [191]:
print("value is : ",a3+55)
print("value is : ",a3-10)
print("value is : ",a3*12)
print("value is : ",a3/6)
print("value is : ",a3//6)
print("value is : ",a3**2)
print("value is : ",a3%6)

value is :  [55 56 57 58 59]
value is :  [-10  -9  -8  -7  -6]
value is :  [ 0 12 24 36 48]
value is :  [0.         0.16666667 0.33333333 0.5        0.66666667]
value is :  [0 0 0 0 0]
value is :  [ 0  1  4  9 16]
value is :  [0 1 2 3 4]


In [202]:
a4=np.arange(4).reshape(2,2)
a5=np.arange(4).reshape(2,2)

In [203]:
np.add(a4,a5)

array([[0, 2],
       [4, 6]])

In [205]:
np.average(a4)

1.5

### Trigonometric function
- sin thetha
 - cos
 - tan

In [209]:
#not more than value of 1

In [223]:
angle=np.linspace(0,np.pi,3) #most use ful function in data scientist using this

In [225]:
angle

array([0.        , 1.57079633, 3.14159265])

In [229]:
np.tan(angle)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [230]:
value_of_ouput=[-1,0,1]

In [234]:
np.arccos(value_of_ouput)

array([3.14159265, 1.57079633, 0.        ])