# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by Nagendra yadav

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
age=np.random.randint(10,28,size=(5,5))
print(age)
print("my age",age.size)

[[15 15 20 13 14]
 [15 23 25 23 12]
 [16 21 25 15 17]
 [16 22 20 19 27]
 [16 14 17 25 21]]
my age 25


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
ex=np.arange(1,50,2)
print(ex)
print(len(ex))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
sol2=np.linspace(4,7,27)
print(sol2)
print("length",len(sol2))

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]
length 27


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
sol4=np.round(np.random.rand(5,4),2)
print(sol4)


[[0.32 0.75 0.09 0.2 ]
 [0.31 0.15 0.27 0.4 ]
 [0.62 0.52 0.11 0.78]
 [0.57 0.35 0.44 0.89]
 [0.86 0.94 0.74 0.39]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution
sol5=np.random.randint(5,15,size=(5,5))
print(sol5)

[[13 14 11 13 11]
 [ 6  7 12  6 11]
 [ 8  5 13 11 11]
 [11 11  9  8  6]
 [10 14  5  9 13]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution
#sol6=np.zeros(np.random.randint(1,20),dtype='int32')
#print(sol6)


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution
sol7=np.ones((np.random.randint(1,20),np.random.randint(1,20)),dtype='float32')
print(sol7)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution
a=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(a.shape)
print(type(a))
print(a.dtype)
print(a)

(5, 5)
<class 'numpy.ndarray'>
int32
[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
# Solution
print("the center element is :",a[2,2])


the center element is : 3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
print(a[2])

[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
print(a[:,3])

[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution
#a[[0,4]][:,[0,4]] this one good
x=a[[0,4],:]
y=x[:,[0,4]]
y

array([[ 9, 45],
       [23,  8]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 
m1=a[0:2,2:4]
m3=a[2:5,2:5]
m2=a[3:5,0:2]
print(m1)
print(m2)
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
n1=m1.reshape((1,4)) #([1,-1])
print(n1)
n2=m2.reshape((1,4)) #([1,np.size(m2)])
print(n2)
n3=m3.reshape((1,9)) #([1,-1])
print(n3)

[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution
print('Row wise :\n',np.concatenate((m1,m2)))
print('Column wise :\n',np.concatenate((m1,m2),axis=1))

Row wise :
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
Column wise :
 [[50 34  7  8]
 [34 65 23 12]]


In [16]:
mh=np.hstack([m1,m2]) #horizontal stack
mv=np.vstack([m1,m2]) #vertical stack 
print(mh,mv,sep="\n")

[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


In [17]:

print(np.concatenate([m1,m2],axis=1))
print(np.concatenate([m1,m2]))

[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [18]:
# Solution
add=m1+m2
mul=m1*m2
sub=m1-m2
div=m1/m2
print(add)
print(mul)
print(sub)
print(div)


[[57 42]
 [57 77]]
[[350 272]
 [782 780]]
[[43 26]
 [11 53]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [19]:
# Solution

new_m=m3[1:,:-1]
print(new_m+m1)

[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [20]:
# Solution
#x = np.mean(m1,1)
#m4 = np.vstack((m1,x))
#m4

new_m1=np.mean(m1[:,0])
new_m2=np.mean(m1[:,1])
print(new_m1,new_m2)
new__m3=np.hstack([new_m1,new_m2])
print(new__m3)
new_var=np.mean(m1,axis=0) #axis =0 is using for computing
print(new_var)
m4=np.vstack([m1,new_var])
print(m4)

42.0 49.5
[42.  49.5]
[42.  49.5]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [21]:
# Solution
print(m4,m3,sep='\n')
print("Multiplaction",(np.dot(m3,m4)))

[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
Multiplaction [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [22]:
# Solution
print(min(np.mean(a,axis=1)))
print(max(np.mean(a,axis=1)))
print(min(np.var(a,axis=1)))
print(max(np.var(a,axis=1)))
print(min(np.std(a,axis=1)))
print(max(np.std(a,axis=1)))

11.2
32.6
39.760000000000005
820.1600000000001
6.305553108173779
28.63843571147


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [23]:
# Solution 
balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],
               ['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])
#run 
run=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],
               ['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
print(balls)
ball=balls[:,1:5]
print('\n the ball matrix \n ',ball)
ball1=ball.astype("int32") #to make this as integer
runs=run[:,1:5]
run1=runs.astype("int32") #to make this as integer
print('\n the Run matrix \n ',runs)
strike=run1/ball1 *100
print(strike)
sr=strike.mean(axis=1)
print("\n the strike for each player \n ",sr)
sr1=sr.reshape([5,1])
player_sr=np.concatenate([balls,sr1],axis=1)
print("\n player ball faced with strike run rate \n",player_sr)
ind=sr.argsort() #accessending
final_output=player_sr[ind,:][::-1]
print("\n final list \n",final_output)

[['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]

 the ball matrix 
  [['50' '42' '22' '78']
 ['95' '8' '65' '43']
 ['9' '100' '7' '101']
 ['27' '3' '11' '31']
 ['24' '20' '36' '27']]

 the Run matrix 
  [['54' '60' '10' '65']
 ['102' '2' '78' '32']
 ['3' '110' '1' '92']
 ['56' '6' '12' '42']
 ['12' '8' '22' '11']]
[[108.         142.85714286  45.45454545  83.33333333]
 [107.36842105  25.         120.          74.41860465]
 [ 33.33333333 110.          14.28571429  91.08910891]
 [207.40740741 200.         109.09090909 135.48387097]
 [ 50.          40.          61.11111111  40.74074074]]

 the strike for each player 
  [ 94.91125541  81.69675643  62.17703913 162.99554687  47.96296296]

 player ball faced with strike run rate 
 [['MSD' '50' '42' '22' '78' '94.91125541125541']
 ['Kholi' '95' '8' '65' '43' '81.69675642594859']
 ['Rohit' '9' '100' '7' '101' '62.17703913248468']
 ['Rahul' '

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [33]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
pass_ind=np.where(Marks>50)
pass_marks=marks[pass_ind]
fail_ind=np.where(marks<50)
fail_marks=Marks[fail_ind]
#a=Marks[Marks<50]
print('student passed : ',len(pass_marks))
print('student failed : ',fail_marks)
print('student failed : ',pass_marks)

student passed :  7
student failed :  [47 48 39]
student failed :  [65 84 56 89 98 77 80]


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [49]:
new_marks=marks.copy()
new_marks
mercy_marks=np.where((new_marks>=45) & (new_marks<=49))
new_marks[mercy_marks]=new_marks[mercy_marks]+5
bouns_marks=np.where((new_marks>80) & (new_marks<=95))
new_marks[bouns_marks]=new_marks[bouns_marks]+5

new_marks1=np.where(new_marks>95)
new_marks[bouns_marks]=100


print('\n Actual student marks \n', marks)
print('\n New_marks which provides to  student marks \n', new_marks)
actual_pass_marks=(len(marks[np.where(marks>=50)])/len(marks))*100
our_new_marks=(len(new_marks[np.where(new_marks>=50)])/len(new_marks))*100
inc_in_percentage=our_new_marks-actual_pass_marks    
print("\n the  pertange increase in marks \n",inc_in_percentage)


 Actual student marks 
 [65 84 47 56 89 98 48 77 80 39]

 New_marks which provides to  student marks 
 [ 65 100  52  56 100  98  53  77  80  39]

 the  pertange increase in marks 
 20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [73]:
import time
x=range(1,60000)
y=range(1,60000)
out=[]
st=time.time()
for i,j in zip(x,y):
    out.append((x[i-1]*x[i-1]+8)/y[i-1])
print('time taken to complete the computation using list : ',(time.time()-st)*1000)

x_arr=np.arange(1,60000)
y_arr=np.arange(1,60000)
st_t=time.time()
out_arr=((x_arr*x_arr)+8)/y_arr
print('time taken to complete the computation using Numpy : ',(time.time()-st_t)*1000)

time taken to complete the computation using list :  43.999671936035156
time taken to complete the computation using Numpy :  1.0123252868652344


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [25]:
https://github.com/Akashkumar201/DataScience/blob/master/NumPy/Numpy_Exercise.ipynb
