# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by Nagendra yadav

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [8]:
#Solution
import numpy as np
age=np.random.randint(10,28,size=(5,5))
print(age)
print("my age",age.size)

[[16 27 25 12 19]
 [20 23 23 26 14]
 [19 26 26 14 11]
 [10 10 19 26 19]
 [13 24 22 27 16]]
my age 25


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [17]:
# Solution
ex=np.arange(1,50,2)
print(ex)
print(len(ex))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [22]:
# Solution
sol2=np.linspace(4,7,27)
print(sol2)
print("length",len(sol2))

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]
length 27


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [27]:
# Solution
sol4=np.round(np.random.rand(5,4),2)
print(sol4)


[[0.77 0.56 0.77 0.52]
 [0.59 0.97 0.37 0.1 ]
 [0.89 0.29 0.82 0.37]
 [0.48 0.51 0.72 0.54]
 [0.41 0.99 0.53 0.16]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [29]:
# Solution
sol5=np.random.randint(5,15,size=(5,5))
print(sol5)

[[ 8  9  7  7 14]
 [ 9 10  9  5  6]
 [ 5 11  5 10  6]
 [ 7  7 10  8 14]
 [14 12 13  7 11]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [36]:
# Solution
#sol6=np.zeros(np.random.randint(1,20),dtype='int32')
#print(sol6)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [8]:
# Solution



#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
# Solution


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:
# Solution



#### 10. Print the all the elements of 3rd row of the matrix

In [11]:
# Solution


#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
# Solution


#### 12. Print the 4 corner pixels of the matrix

In [13]:
# Solution


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [14]:
# Solution 


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
# Solution


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
# Solution


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
# Solution


#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
# Solution


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
# Solution


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [22]:
# Solution 


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [25]:
# Solution

